<?php

namespace MusicShareBundle\Repository;

/**
 * PlayListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayListRepository extends \Doctrine\ORM\EntityRepository
{
}
