<?php

namespace MusicShareBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the reatings of Sound.
     * @param   $sound_id
     *
     * @return  Returns count
     *
     */
    public function getLikedRating($sound_id)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(r) FROM MusicShareBundle:Rating r where r.liked > 0 and r.soundId = ?1');
        $query->setParameter(1, $sound_id);
        $count = $query->getSingleScalarResult();
        return $count;
    }


    /**
     * Get the reatings of Sound.
     * @param   $sound_id
     *
     * @return  Returns count
     *
     */
    public function getDisLikedRating($sound_id)
    {

        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(r) FROM MusicShareBundle:Rating r where r.liked < 0 and r.soundId = ?1');
        $query->setParameter(1, $sound_id);
        $count = $query->getSingleScalarResult();
        return $count;
    }
}
